### ISSUE TITLE
Enhancement: Split config object for long and short positions 

### ISSUE THREAD

**Issue by maimas** [OrgTBoot/AlpacaTrader#1]
P3

Eventually, we might want to trade both sides (long/short)... proposing to branch config object for each side.
```
config = {
 long : {....}
 short: {...}
}
```

https://github.com/OrgTBoot/AlpacaTrader/blob/4524e9d0a4b86f6113526c4566c041a4140df046/alpaca-lambda/src/config.ts#L1

**Comment by vladislavmunteanu** [comment]
added the branch for long / short
