### ISSUE TITLE
Solution for secrets

### ISSUE THREAD

**Issue by maimas** [OrgTBoot/AlpacaTrader#8]
Would be great to find a solution for secrets so that we are not pushing accidentally them to Github or deploy lambda without them.

**Comment by vladislavmunteanu** [comment]
We can store them in SSM and update CF to create environment variables for the lambda function.

**Comment by vladislavmunteanu** [comment]
> Would be great to find a solution for secrets so that we are not pushing accidentally them to Github or deploy lambda without them.

We can store them in SSM and update CF to create environment variables for the lambda function.

**Comment by vladislavmunteanu** [comment]
Moved credentials to AWS SM, please have below parameters added into your AWS account:

<img width="1634" alt="Screenshot 2023-03-11 at 4 07 03 PM" src="https://user-images.githubusercontent.com/8665239/224517118-22a9de94-dfe2-4731-acb5-1fb605aa14d6.png">
